#!/usr/bin/env bash

# This script displays "Best School" 10 times using a for loop.

#!/usr/bin/env bash
# displays Best School 10 times.

for (( aac=1; aac<10; aac++ ))
do
    echo "Best School"
done
