#!/usr/bin/env bash
# Displays hours from 0 to 12 and minutes from 1 to 59

hour=0

while [ $hour -lt 13 ]; do
      echo "Hour: $hour"
      a=1
      while [ $a -le 59 ]; do
      	  echo "$a"
	  a=$((a+1))
      done
      hour=$((hour+1))
done
